app = 'flight-quest'
primary_region = 'cdg'

[build]
  dockerfile = "Dockerfile.server"

[[services]]
  protocol = "udp"
  internal_port = 7777
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 7777
